# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VDatosVuelos.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_VDatosVuelo(object):
    def setupUi(self, VDatosVuelo):
        VDatosVuelo.setObjectName("VDatosVuelo")
        VDatosVuelo.setWindowModality(QtCore.Qt.ApplicationModal)
        VDatosVuelo.resize(860, 350)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(VDatosVuelo.sizePolicy().hasHeightForWidth())
        VDatosVuelo.setSizePolicy(sizePolicy)
        VDatosVuelo.setMinimumSize(QtCore.QSize(860, 350))
        VDatosVuelo.setMaximumSize(QtCore.QSize(860, 350))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/SIPaF.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        VDatosVuelo.setWindowIcon(icon)
        VDatosVuelo.setStyleSheet("font: 14pt \"Arial Rounded MT Bold\";\n"
"\n"
"background-color: rgb(255, 255, 255);")
        self.verticalLayout = QtWidgets.QVBoxLayout(VDatosVuelo)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_principal = QtWidgets.QFrame(VDatosVuelo)
        self.frame_principal.setStyleSheet("QPushButton{\n"
"    background-color: rgb(245, 245, 245);\n"
"}")
        self.frame_principal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_principal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_principal.setObjectName("frame_principal")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_principal)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_etiquetas = QtWidgets.QFrame(self.frame_principal)
        self.frame_etiquetas.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_etiquetas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_etiquetas.setObjectName("frame_etiquetas")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_etiquetas)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(14)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_ancho_cubierto = QtWidgets.QLabel(self.frame_etiquetas)
        self.lbl_ancho_cubierto.setObjectName("lbl_ancho_cubierto")
        self.verticalLayout_2.addWidget(self.lbl_ancho_cubierto)
        self.lbl_largo_cubierto = QtWidgets.QLabel(self.frame_etiquetas)
        self.lbl_largo_cubierto.setObjectName("lbl_largo_cubierto")
        self.verticalLayout_2.addWidget(self.lbl_largo_cubierto)
        self.lbl_overlap_horizontal = QtWidgets.QLabel(self.frame_etiquetas)
        self.lbl_overlap_horizontal.setObjectName("lbl_overlap_horizontal")
        self.verticalLayout_2.addWidget(self.lbl_overlap_horizontal)
        self.lbl_overlap_vertical = QtWidgets.QLabel(self.frame_etiquetas)
        self.lbl_overlap_vertical.setObjectName("lbl_overlap_vertical")
        self.verticalLayout_2.addWidget(self.lbl_overlap_vertical)
        self.lbl_altura_vuelo = QtWidgets.QLabel(self.frame_etiquetas)
        self.lbl_altura_vuelo.setObjectName("lbl_altura_vuelo")
        self.verticalLayout_2.addWidget(self.lbl_altura_vuelo)
        self.lbl_orientacion = QtWidgets.QLabel(self.frame_etiquetas)
        self.lbl_orientacion.setObjectName("lbl_orientacion")
        self.verticalLayout_2.addWidget(self.lbl_orientacion)
        self.lbl_fecha_vuelo = QtWidgets.QLabel(self.frame_etiquetas)
        self.lbl_fecha_vuelo.setObjectName("lbl_fecha_vuelo")
        self.verticalLayout_2.addWidget(self.lbl_fecha_vuelo)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.pb_guardar = QtWidgets.QPushButton(self.frame_etiquetas)
        self.pb_guardar.setObjectName("pb_guardar")
        self.verticalLayout_2.addWidget(self.pb_guardar)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout.addWidget(self.frame_etiquetas)
        self.frame_entradas = QtWidgets.QFrame(self.frame_principal)
        self.frame_entradas.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_entradas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_entradas.setObjectName("frame_entradas")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_entradas)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(8)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.le_ancho_cubierto = QtWidgets.QLineEdit(self.frame_entradas)
        self.le_ancho_cubierto.setObjectName("le_ancho_cubierto")
        self.verticalLayout_3.addWidget(self.le_ancho_cubierto)
        self.le_largo_cubierto = QtWidgets.QLineEdit(self.frame_entradas)
        self.le_largo_cubierto.setObjectName("le_largo_cubierto")
        self.verticalLayout_3.addWidget(self.le_largo_cubierto)
        self.le_overlap_horizontal = QtWidgets.QLineEdit(self.frame_entradas)
        self.le_overlap_horizontal.setObjectName("le_overlap_horizontal")
        self.verticalLayout_3.addWidget(self.le_overlap_horizontal)
        self.le_overlap_vertical = QtWidgets.QLineEdit(self.frame_entradas)
        self.le_overlap_vertical.setObjectName("le_overlap_vertical")
        self.verticalLayout_3.addWidget(self.le_overlap_vertical)
        self.le_altura_vuelo = QtWidgets.QLineEdit(self.frame_entradas)
        self.le_altura_vuelo.setObjectName("le_altura_vuelo")
        self.verticalLayout_3.addWidget(self.le_altura_vuelo)
        self.cb_orientacion = QtWidgets.QComboBox(self.frame_entradas)
        self.cb_orientacion.setObjectName("cb_orientacion")
        self.cb_orientacion.addItem("")
        self.cb_orientacion.addItem("")
        self.verticalLayout_3.addWidget(self.cb_orientacion)
        self.dTE_fecha_vuelo = QtWidgets.QDateTimeEdit(self.frame_entradas)
        self.dTE_fecha_vuelo.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(1950, 9, 14), QtCore.QTime(0, 0, 0)))
        self.dTE_fecha_vuelo.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.dTE_fecha_vuelo.setCalendarPopup(True)
        self.dTE_fecha_vuelo.setTimeSpec(QtCore.Qt.LocalTime)
        self.dTE_fecha_vuelo.setObjectName("dTE_fecha_vuelo")
        self.verticalLayout_3.addWidget(self.dTE_fecha_vuelo)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.frame_botones_entradas = QtWidgets.QFrame(self.frame_entradas)
        self.frame_botones_entradas.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_botones_entradas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_botones_entradas.setObjectName("frame_botones_entradas")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_botones_entradas)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pb_atras = QtWidgets.QPushButton(self.frame_botones_entradas)
        self.pb_atras.setObjectName("pb_atras")
        self.horizontalLayout_2.addWidget(self.pb_atras)
        self.pb_cancelar = QtWidgets.QPushButton(self.frame_botones_entradas)
        self.pb_cancelar.setObjectName("pb_cancelar")
        self.horizontalLayout_2.addWidget(self.pb_cancelar)
        self.verticalLayout_3.addWidget(self.frame_botones_entradas)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.horizontalLayout.addWidget(self.frame_entradas)
        self.frame_imagen_vuelo = QtWidgets.QFrame(self.frame_principal)
        self.frame_imagen_vuelo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_imagen_vuelo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_imagen_vuelo.setObjectName("frame_imagen_vuelo")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_imagen_vuelo)
        self.verticalLayout_4.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.img_vuelo = QtWidgets.QLabel(self.frame_imagen_vuelo)
        self.img_vuelo.setText("")
        self.img_vuelo.setPixmap(QtGui.QPixmap("images/flightProperties.png"))
        self.img_vuelo.setScaledContents(True)
        self.img_vuelo.setObjectName("img_vuelo")
        self.verticalLayout_4.addWidget(self.img_vuelo)
        self.horizontalLayout.addWidget(self.frame_imagen_vuelo)
        self.verticalLayout.addWidget(self.frame_principal)

        self.retranslateUi(VDatosVuelo)
        QtCore.QMetaObject.connectSlotsByName(VDatosVuelo)

    def retranslateUi(self, VDatosVuelo):
        _translate = QtCore.QCoreApplication.translate
        VDatosVuelo.setWindowTitle(_translate("VDatosVuelo", "Datos de Vuelo"))
        self.lbl_ancho_cubierto.setToolTip(_translate("VDatosVuelo", "La distancia del ancho cubierto por el vuelo."))
        self.lbl_ancho_cubierto.setText(_translate("VDatosVuelo", "Ancho cubierto:"))
        self.lbl_largo_cubierto.setToolTip(_translate("VDatosVuelo", "La distancia del largo cubierto por el vuelo."))
        self.lbl_largo_cubierto.setText(_translate("VDatosVuelo", "Largo cubierto:"))
        self.lbl_overlap_horizontal.setToolTip(_translate("VDatosVuelo", "El porcentaje de solapamiento horizontal entre imagenes."))
        self.lbl_overlap_horizontal.setText(_translate("VDatosVuelo", "Overlap horizontal:"))
        self.lbl_overlap_vertical.setToolTip(_translate("VDatosVuelo", "El porcentaje de solapamiento vertical entre imagenes."))
        self.lbl_overlap_vertical.setText(_translate("VDatosVuelo", "Overlap vertical:"))
        self.lbl_altura_vuelo.setToolTip(_translate("VDatosVuelo", "Altura a la que el vuelo fue realizado."))
        self.lbl_altura_vuelo.setText(_translate("VDatosVuelo", "Altura vuelo:"))
        self.lbl_orientacion.setText(_translate("VDatosVuelo", "Orientación"))
        self.lbl_fecha_vuelo.setToolTip(_translate("VDatosVuelo", "El día y la hora en la que se realizó el vuelo."))
        self.lbl_fecha_vuelo.setText(_translate("VDatosVuelo", "Fecha vuelo:"))
        self.pb_guardar.setText(_translate("VDatosVuelo", "Guardar"))
        self.cb_orientacion.setItemText(0, _translate("VDatosVuelo", "Horizontal"))
        self.cb_orientacion.setItemText(1, _translate("VDatosVuelo", "Vertical"))
        self.pb_atras.setText(_translate("VDatosVuelo", "Atras"))
        self.pb_cancelar.setText(_translate("VDatosVuelo", "Cancelar"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     VDatosVuelo = QtWidgets.QWidget()
#     ui = Ui_VDatosVuelo()
#     ui.setupUi(VDatosVuelo)
#     VDatosVuelo.show()
#     sys.exit(app.exec_())

