# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VistaEDT.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_VEDT(object):
    def setupUi(self, VEDT):
        VEDT.setObjectName("VEDT")
        VEDT.resize(1244, 843)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(172)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(VEDT.sizePolicy().hasHeightForWidth())
        VEDT.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        VEDT.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/SIPaF.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        VEDT.setWindowIcon(icon)
        VEDT.setAutoFillBackground(True)
        VEDT.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(VEDT)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_13.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(250, 250, 250);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_3.setStyleSheet("QPushButton{\n"
"    border-radius:10px;\n"
"    background-color: rgb(240, 240, 240);\n"
"}\n"
"\n"
"QFrame{\n"
"    \n"
"    background-color: rgb(240, 240, 240);\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pbCrearProyecto = QtWidgets.QPushButton(self.frame_3)
        self.pbCrearProyecto.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/newProject.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbCrearProyecto.setIcon(icon1)
        self.pbCrearProyecto.setObjectName("pbCrearProyecto")
        self.horizontalLayout_2.addWidget(self.pbCrearProyecto)
        self.pbEditarPropiedades = QtWidgets.QPushButton(self.frame_3)
        self.pbEditarPropiedades.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/properties.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbEditarPropiedades.setIcon(icon2)
        self.pbEditarPropiedades.setObjectName("pbEditarPropiedades")
        self.horizontalLayout_2.addWidget(self.pbEditarPropiedades)
        self.pbIniciarProceso = QtWidgets.QPushButton(self.frame_3)
        self.pbIniciarProceso.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbIniciarProceso.setIcon(icon3)
        self.pbIniciarProceso.setObjectName("pbIniciarProceso")
        self.horizontalLayout_2.addWidget(self.pbIniciarProceso)
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(5, 20))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("images/verticalLine.png"))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.pbImprimir = QtWidgets.QPushButton(self.frame_3)
        self.pbImprimir.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/print.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbImprimir.setIcon(icon4)
        self.pbImprimir.setObjectName("pbImprimir")
        self.horizontalLayout_2.addWidget(self.pbImprimir)
        self.pbComparar = QtWidgets.QPushButton(self.frame_3)
        self.pbComparar.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("images/compare.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbComparar.setIcon(icon5)
        self.pbComparar.setObjectName("pbComparar")
        self.horizontalLayout_2.addWidget(self.pbComparar)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(240, 240, 240);\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 2, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(240, 240, 240);\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_2.setContentsMargins(2, 2, 1, 2)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_7 = QtWidgets.QFrame(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_7.setStyleSheet("border-radius:5px;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.textoBuscar = QtWidgets.QLineEdit(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textoBuscar.sizePolicy().hasHeightForWidth())
        self.textoBuscar.setSizePolicy(sizePolicy)
        self.textoBuscar.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.textoBuscar.setFont(font)
        self.textoBuscar.setToolTipDuration(-1)
        self.textoBuscar.setAutoFillBackground(False)
        self.textoBuscar.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"background-color: rgb(253, 253, 253);")
        self.textoBuscar.setInputMethodHints(QtCore.Qt.ImhNone)
        self.textoBuscar.setInputMask("")
        self.textoBuscar.setText("")
        self.textoBuscar.setMaxLength(35)
        self.textoBuscar.setFrame(True)
        self.textoBuscar.setClearButtonEnabled(True)
        self.textoBuscar.setObjectName("textoBuscar")
        self.horizontalLayout_5.addWidget(self.textoBuscar)
        self.pbBuscar = QtWidgets.QPushButton(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbBuscar.sizePolicy().hasHeightForWidth())
        self.pbBuscar.setSizePolicy(sizePolicy)
        self.pbBuscar.setMinimumSize(QtCore.QSize(16, 16))
        self.pbBuscar.setMaximumSize(QtCore.QSize(30, 25))
        self.pbBuscar.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.pbBuscar.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("images/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbBuscar.setIcon(icon6)
        self.pbBuscar.setIconSize(QtCore.QSize(16, 16))
        self.pbBuscar.setObjectName("pbBuscar")
        self.horizontalLayout_5.addWidget(self.pbBuscar)
        self.verticalLayout_2.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.frame_5)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.vistaArbolProyectos = QtWidgets.QTreeView(self.frame_8)
        self.vistaArbolProyectos.setAutoFillBackground(True)
        self.vistaArbolProyectos.setStyleSheet("background-color: rgb(253, 253, 253);\n"
"border-radius:40px;")
        self.vistaArbolProyectos.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.vistaArbolProyectos.setFrameShadow(QtWidgets.QFrame.Plain)
        self.vistaArbolProyectos.setLineWidth(1)
        self.vistaArbolProyectos.setMidLineWidth(0)
        self.vistaArbolProyectos.setObjectName("vistaArbolProyectos")
        self.verticalLayout_3.addWidget(self.vistaArbolProyectos)
        self.verticalLayout_2.addWidget(self.frame_8)
        self.horizontalLayout_4.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(253, 253, 253);\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabEDT = QtWidgets.QTabWidget(self.frame_6)
        self.tabEDT.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tabEDT.setFont(font)
        self.tabEDT.setStyleSheet("QTabWidget{\n"
"    \n"
"    font: 10pt \"Arial Rounded MT Bold\";\n"
"}")
        self.tabEDT.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabEDT.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabEDT.setElideMode(QtCore.Qt.ElideNone)
        self.tabEDT.setDocumentMode(False)
        self.tabEDT.setTabsClosable(True)
        self.tabEDT.setTabBarAutoHide(True)
        self.tabEDT.setObjectName("tabEDT")
        self.inicio = QtWidgets.QWidget()
        self.inicio.setObjectName("inicio")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.inicio)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lblInicio = QtWidgets.QLabel(self.inicio)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(36)
        self.lblInicio.setFont(font)
        self.lblInicio.setScaledContents(False)
        self.lblInicio.setAlignment(QtCore.Qt.AlignCenter)
        self.lblInicio.setWordWrap(True)
        self.lblInicio.setObjectName("lblInicio")
        self.verticalLayout_5.addWidget(self.lblInicio)
        self.tabEDT.addTab(self.inicio, "")
        self.resultados = QtWidgets.QWidget()
        self.resultados.setObjectName("resultados")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.resultados)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_15 = QtWidgets.QFrame(self.resultados)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(6)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.scrollArea = QtWidgets.QScrollArea(self.frame_15)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1049, 733))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_17 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_17.setStyleSheet("font: 14pt \"Arial Rounded MT Bold\";")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_17)
        self.gridLayout.setContentsMargins(5, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(5)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(self.frame_17)
        self.label_7.setFrameShape(QtWidgets.QFrame.Box)
        self.label_7.setText("")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 1, 1, 1)
        self.lbl_fechaVuelo = QtWidgets.QLabel(self.frame_17)
        self.lbl_fechaVuelo.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_fechaVuelo.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lbl_fechaVuelo.setText("")
        self.lbl_fechaVuelo.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_fechaVuelo.setObjectName("lbl_fechaVuelo")
        self.gridLayout.addWidget(self.lbl_fechaVuelo, 1, 1, 1, 1)
        self.lbl_anchoCubierto = QtWidgets.QLabel(self.frame_17)
        self.lbl_anchoCubierto.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_anchoCubierto.setText("")
        self.lbl_anchoCubierto.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_anchoCubierto.setObjectName("lbl_anchoCubierto")
        self.gridLayout.addWidget(self.lbl_anchoCubierto, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_17)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame_17)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 5, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_17)
        self.label_5.setFrameShape(QtWidgets.QFrame.Box)
        self.label_5.setText("")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_17)
        self.label_9.setFrameShape(QtWidgets.QFrame.Box)
        self.label_9.setText("")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 7, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_17)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_17)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 7, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.frame_17)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 8, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.frame_17)
        self.label_13.setFrameShape(QtWidgets.QFrame.Box)
        self.label_13.setText("")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 5, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_17)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 4, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frame_17)
        self.label_11.setFrameShape(QtWidgets.QFrame.Box)
        self.label_11.setText("")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 4, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_17)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 7, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.frame_17)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("font: 20pt \"Arial Rounded MT Bold\";")
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 0, 0, 1, 1)
        self.lbl_fechaVuelo_2 = QtWidgets.QLabel(self.frame_17)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_fechaVuelo_2.setFont(font)
        self.lbl_fechaVuelo_2.setStyleSheet("font: 20pt \"Arial Rounded MT Bold\";")
        self.lbl_fechaVuelo_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_fechaVuelo_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lbl_fechaVuelo_2.setText("")
        self.lbl_fechaVuelo_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_fechaVuelo_2.setObjectName("lbl_fechaVuelo_2")
        self.gridLayout.addWidget(self.lbl_fechaVuelo_2, 0, 1, 1, 2)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 2)
        self.gridLayout.setColumnStretch(2, 5)
        self.verticalLayout_14.addWidget(self.frame_17)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_12.addWidget(self.scrollArea)
        self.verticalLayout_10.addWidget(self.frame_15)
        self.tabEDT.addTab(self.resultados, "")
        self.ortofotoRGB = QtWidgets.QWidget()
        self.ortofotoRGB.setObjectName("ortofotoRGB")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.ortofotoRGB)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_9 = QtWidgets.QFrame(self.ortofotoRGB)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_7.setContentsMargins(0, 2, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_10 = QtWidgets.QFrame(self.frame_9)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.checkBox = QtWidgets.QCheckBox(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        self.checkBox.setFont(font)
        self.checkBox.setIconSize(QtCore.QSize(30, 30))
        self.checkBox.setChecked(True)
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_6.addWidget(self.checkBox)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.verticalLayout_7.addWidget(self.frame_10)
        self.frame_11 = QtWidgets.QFrame(self.frame_9)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_7.addWidget(self.frame_11)
        self.verticalLayout_7.setStretch(0, 1)
        self.verticalLayout_7.setStretch(1, 100)
        self.verticalLayout_6.addWidget(self.frame_9)
        self.tabEDT.addTab(self.ortofotoRGB, "")
        self.ortofotoTermica = QtWidgets.QWidget()
        self.ortofotoTermica.setObjectName("ortofotoTermica")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.ortofotoTermica)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_12 = QtWidgets.QFrame(self.ortofotoTermica)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_9.setContentsMargins(0, 2, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_13 = QtWidgets.QFrame(self.frame_12)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_2.sizePolicy().hasHeightForWidth())
        self.checkBox_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setIconSize(QtCore.QSize(30, 30))
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setTristate(False)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_7.addWidget(self.checkBox_2)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.verticalLayout_9.addWidget(self.frame_13)
        self.frame_14 = QtWidgets.QFrame(self.frame_12)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_9.addWidget(self.frame_14)
        self.verticalLayout_9.setStretch(0, 1)
        self.verticalLayout_9.setStretch(1, 100)
        self.verticalLayout_8.addWidget(self.frame_12)
        self.tabEDT.addTab(self.ortofotoTermica, "")
        self.graficas = QtWidgets.QWidget()
        self.graficas.setObjectName("graficas")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.graficas)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_16 = QtWidgets.QFrame(self.graficas)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_11.addWidget(self.frame_16)
        self.tabEDT.addTab(self.graficas, "")
        self.verticalLayout_4.addWidget(self.tabEDT)
        self.horizontalLayout_4.addWidget(self.frame_6)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 6)
        self.horizontalLayout_3.addWidget(self.frame_4)
        self.verticalLayout.addWidget(self.frame_2)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 25)
        self.verticalLayout_13.addWidget(self.frame)
        VEDT.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(VEDT)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1244, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        self.menubar.setPalette(palette)
        self.menubar.setStyleSheet("background-color: rgb(245, 245, 245);")
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        self.menuProyecto = QtWidgets.QMenu(self.menubar)
        self.menuProyecto.setObjectName("menuProyecto")
        self.menuReporte = QtWidgets.QMenu(self.menubar)
        self.menuReporte.setObjectName("menuReporte")
        self.menuAyuda = QtWidgets.QMenu(self.menubar)
        self.menuAyuda.setObjectName("menuAyuda")
        VEDT.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(VEDT)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusbar.sizePolicy().hasHeightForWidth())
        self.statusbar.setSizePolicy(sizePolicy)
        self.statusbar.setObjectName("statusbar")
        VEDT.setStatusBar(self.statusbar)
        self.actionAbrir = QtWidgets.QAction(VEDT)
        self.actionAbrir.setObjectName("actionAbrir")
        self.actionGuardar = QtWidgets.QAction(VEDT)
        self.actionGuardar.setObjectName("actionGuardar")
        self.actionGuardar_como = QtWidgets.QAction(VEDT)
        self.actionGuardar_como.setObjectName("actionGuardar_como")
        self.actionSalir = QtWidgets.QAction(VEDT)
        self.actionSalir.setObjectName("actionSalir")
        self.actionEstablecer_correo = QtWidgets.QAction(VEDT)
        self.actionEstablecer_correo.setObjectName("actionEstablecer_correo")
        self.actionImprimir = QtWidgets.QAction(VEDT)
        self.actionImprimir.setObjectName("actionImprimir")
        self.actionCompartir = QtWidgets.QAction(VEDT)
        self.actionCompartir.setObjectName("actionCompartir")
        self.actionNuevo = QtWidgets.QAction(VEDT)
        self.actionNuevo.setObjectName("actionNuevo")
        self.actionIniciar = QtWidgets.QAction(VEDT)
        self.actionIniciar.setObjectName("actionIniciar")
        self.actionPropiedades = QtWidgets.QAction(VEDT)
        self.actionPropiedades.setObjectName("actionPropiedades")
        self.actionEstablecer_correo_2 = QtWidgets.QAction(VEDT)
        self.actionEstablecer_correo_2.setObjectName("actionEstablecer_correo_2")
        self.actionNuevo_2 = QtWidgets.QAction(VEDT)
        self.actionNuevo_2.setObjectName("actionNuevo_2")
        self.actionGuardar_2 = QtWidgets.QAction(VEDT)
        self.actionGuardar_2.setObjectName("actionGuardar_2")
        self.actionGuardar_como_2 = QtWidgets.QAction(VEDT)
        self.actionGuardar_como_2.setObjectName("actionGuardar_como_2")
        self.actionAbrir_2 = QtWidgets.QAction(VEDT)
        self.actionAbrir_2.setObjectName("actionAbrir_2")
        self.actionAbrir_3 = QtWidgets.QAction(VEDT)
        self.actionAbrir_3.setObjectName("actionAbrir_3")
        self.actionVer_gr_fica = QtWidgets.QAction(VEDT)
        self.actionVer_gr_fica.setObjectName("actionVer_gr_fica")
        self.actionGuardar_gr_fica = QtWidgets.QAction(VEDT)
        self.actionGuardar_gr_fica.setObjectName("actionGuardar_gr_fica")
        self.actionEliminar = QtWidgets.QAction(VEDT)
        self.actionEliminar.setObjectName("actionEliminar")
        self.menuArchivo.addAction(self.actionNuevo_2)
        self.menuArchivo.addAction(self.actionGuardar)
        self.menuArchivo.addAction(self.actionAbrir)
        self.menuArchivo.addAction(self.actionEliminar)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.actionEstablecer_correo_2)
        self.menuProyecto.addAction(self.actionNuevo)
        self.menuProyecto.addAction(self.actionAbrir_2)
        self.menuProyecto.addAction(self.actionGuardar_2)
        self.menuProyecto.addAction(self.actionGuardar_como_2)
        self.menuProyecto.addSeparator()
        self.menuProyecto.addAction(self.actionIniciar)
        self.menuProyecto.addAction(self.actionPropiedades)
        self.menuReporte.addAction(self.actionAbrir_3)
        self.menuReporte.addAction(self.actionImprimir)
        self.menuReporte.addAction(self.actionCompartir)
        self.menuReporte.addSeparator()
        self.menuReporte.addAction(self.actionVer_gr_fica)
        self.menuReporte.addAction(self.actionGuardar_gr_fica)
        self.menubar.addAction(self.menuProyecto.menuAction())
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuReporte.menuAction())
        self.menubar.addAction(self.menuAyuda.menuAction())
        # change color of the menu bar only when the mouse is over it
        self.menubar.setStyleSheet("QMenuBar::item {background-color: transparent;}")
        self.menubar.setStyleSheet("QMenuBar::item:selected {background-color: transparent;}")
        self.menubar.setStyleSheet("QMenuBar::item:pressed {background-color: transparent;}")

        self.retranslateUi(VEDT)
        self.tabEDT.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(VEDT)

    def retranslateUi(self, VEDT):
        _translate = QtCore.QCoreApplication.translate
        VEDT.setWindowTitle(_translate("VEDT", "SIPaF"))
        self.pbCrearProyecto.setToolTip(_translate("VEDT", "Crear nuevo proyecto"))
        self.pbEditarPropiedades.setToolTip(_translate("VEDT", "Propiedades del proyecto"))
        self.pbIniciarProceso.setToolTip(_translate("VEDT", "Iniciar el proyecto"))
        self.pbImprimir.setToolTip(_translate("VEDT", "Imprimir reporte"))
        self.pbComparar.setToolTip(_translate("VEDT", "Comparar reportes"))
        self.textoBuscar.setToolTip(_translate("VEDT", "Ingresar nombre de archivo"))
        self.textoBuscar.setPlaceholderText(_translate("VEDT", " Buscar...."))
        self.pbBuscar.setToolTip(_translate("VEDT", "Buscar en EDT"))
        self.lblInicio.setText(_translate("VEDT", "Bienvenido, inicie o abra un proyecto."))
        self.tabEDT.setTabText(self.tabEDT.indexOf(self.inicio), _translate("VEDT", "Inicio"))
        self.label_6.setText(_translate("VEDT", "Cantidad de paneles:"))
        self.label_12.setText(_translate("VEDT", "Overlap vertical:"))
        self.label_3.setText(_translate("VEDT", "Fecha del vuelo:"))
        self.label_8.setText(_translate("VEDT", "Número de paneles defectuosos:"))
        self.label.setText(_translate("VEDT", "Ancho cubierto:"))
        self.label_10.setText(_translate("VEDT", "Overlap horizontal:"))
        self.label_4.setText(_translate("VEDT", "Alto cubierto:"))
        self.label_14.setText(_translate("VEDT", "Nombre del proyecto:"))
        self.tabEDT.setTabText(self.tabEDT.indexOf(self.resultados), _translate("VEDT", "Resultados"))
        self.checkBox.setText(_translate("VEDT", "Mostrar ortofoto RGB con paneles solares dañados identificados"))
        self.tabEDT.setTabText(self.tabEDT.indexOf(self.ortofotoRGB), _translate("VEDT", "Ortofoto RGB"))
        self.checkBox_2.setText(_translate("VEDT", "Mostrar ortofoto térmica con paneles solares dañados identificados"))
        self.tabEDT.setTabText(self.tabEDT.indexOf(self.ortofotoTermica), _translate("VEDT", "Ortofoto Térmica"))
        self.tabEDT.setTabText(self.tabEDT.indexOf(self.graficas), _translate("VEDT", "Gráficas"))
        self.menuArchivo.setTitle(_translate("VEDT", "EDT"))
        self.menuProyecto.setTitle(_translate("VEDT", "Proyecto"))
        self.menuReporte.setTitle(_translate("VEDT", "Reporte"))
        self.menuAyuda.setTitle(_translate("VEDT", "Ayuda"))
        self.actionAbrir.setText(_translate("VEDT", "Cambiar"))
        self.actionGuardar.setText(_translate("VEDT", "Guardar"))
        self.actionGuardar_como.setText(_translate("VEDT", "Guardar como..."))
        self.actionSalir.setText(_translate("VEDT", "Salir"))
        self.actionEstablecer_correo.setText(_translate("VEDT", "Cambiar"))
        self.actionImprimir.setText(_translate("VEDT", "Imprimir"))
        self.actionCompartir.setText(_translate("VEDT", "Compartir"))
        self.actionNuevo.setText(_translate("VEDT", "Nuevo"))
        self.actionIniciar.setText(_translate("VEDT", "Iniciar"))
        self.actionPropiedades.setText(_translate("VEDT", "Propiedades"))
        self.actionEstablecer_correo_2.setText(_translate("VEDT", "Establecer correo"))
        self.actionNuevo_2.setText(_translate("VEDT", "Nuevo"))
        self.actionGuardar_2.setText(_translate("VEDT", "Guardar"))
        self.actionGuardar_como_2.setText(_translate("VEDT", "Guardar como..."))
        self.actionAbrir_2.setText(_translate("VEDT", "Abrir"))
        self.actionAbrir_3.setText(_translate("VEDT", "Abrir"))
        self.actionVer_gr_fica.setText(_translate("VEDT", "Ver gráfica"))
        self.actionGuardar_gr_fica.setText(_translate("VEDT", "Guardar gráfica"))
        self.actionEliminar.setText(_translate("VEDT", "Eliminar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VEDT = QtWidgets.QMainWindow()
    ui = Ui_VEDT()
    ui.setupUi(VEDT)
    VEDT.show()
    sys.exit(app.exec_())

