# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VistaEDT.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_VEDT(object):
    def setupUi(self, VEDT):
        VEDT.setObjectName("VEDT")
        VEDT.resize(1244, 843)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(172)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(VEDT.sizePolicy().hasHeightForWidth())
        VEDT.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        VEDT.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/SIPaF.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        VEDT.setWindowIcon(icon)
        VEDT.setAutoFillBackground(True)
        VEDT.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(VEDT)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_13.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_VEDT = QtWidgets.QFrame(self.centralwidget)
        self.frame_VEDT.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(250, 250, 250);\n"
"}")
        self.frame_VEDT.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_VEDT.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_VEDT.setObjectName("frame_VEDT")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_VEDT)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.barra_tareas = QtWidgets.QFrame(self.frame_VEDT)
        self.barra_tareas.setMaximumSize(QtCore.QSize(16777215, 30))
        self.barra_tareas.setStyleSheet("QPushButton{\n"
	"border-radius:10px;\n"
	"background-color: rgb(240, 240, 240);\n"
"}\n"
"QPushButton:pressed{\n"
	"background-color:  rgb(220, 220, 220);\n"
	"border-radius:2px;\n"
	"border-style: outset;\n"
	"border: 0.5px solid;\n"
	"border-top-color : black;\n" 
    "border-left-color :black;\n"
    "border-right-color :black;\n"
    "border-bottom-color : black;\n"
"}\n"

"QPushButton:hover:!pressed{\n"
	"background-color: white;\n"
"}\n"

"QFrame{\n"
	"background-color: rgb(240, 240, 240);\n"
"}")
        self.barra_tareas.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.barra_tareas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.barra_tareas.setObjectName("barra_tareas")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.barra_tareas)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pb_crear_proyecto = QtWidgets.QPushButton(self.barra_tareas)
        self.pb_crear_proyecto.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/newProject.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_crear_proyecto.setIcon(icon1)
        self.pb_crear_proyecto.setObjectName("pb_crear_proyecto")
        self.horizontalLayout_2.addWidget(self.pb_crear_proyecto)
        self.pb_editar_propiedades = QtWidgets.QPushButton(self.barra_tareas)
        self.pb_editar_propiedades.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/properties.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_editar_propiedades.setIcon(icon2)
        self.pb_editar_propiedades.setObjectName("pb_editar_propiedades")
        self.horizontalLayout_2.addWidget(self.pb_editar_propiedades)
        self.pb_iniciar_proceso = QtWidgets.QPushButton(self.barra_tareas)
        self.pb_iniciar_proceso.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_iniciar_proceso.setIcon(icon3)
        self.pb_iniciar_proceso.setObjectName("pb_iniciar_proceso")
        self.horizontalLayout_2.addWidget(self.pb_iniciar_proceso)
        self.lbl_separador = QtWidgets.QLabel(self.barra_tareas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_separador.sizePolicy().hasHeightForWidth())
        self.lbl_separador.setSizePolicy(sizePolicy)
        self.lbl_separador.setMaximumSize(QtCore.QSize(5, 20))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_separador.setFont(font)
        self.lbl_separador.setText("")
        self.lbl_separador.setPixmap(QtGui.QPixmap("images/verticalLine.png"))
        self.lbl_separador.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_separador.setObjectName("lbl_separador")
        self.horizontalLayout_2.addWidget(self.lbl_separador)
        self.pb_imprimir = QtWidgets.QPushButton(self.barra_tareas)
        self.pb_imprimir.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/print.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_imprimir.setIcon(icon4)
        self.pb_imprimir.setObjectName("pb_imprimir")
        self.horizontalLayout_2.addWidget(self.pb_imprimir)
        self.pb_comparar = QtWidgets.QPushButton(self.barra_tareas)
        self.pb_comparar.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("images/compare.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_comparar.setIcon(icon5)
        self.pb_comparar.setObjectName("pb_comparar")
        self.horizontalLayout_2.addWidget(self.pb_comparar)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addWidget(self.barra_tareas)
        self.frame_2 = QtWidgets.QFrame(self.frame_VEDT)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_VEDT_buttom = QtWidgets.QFrame(self.frame_2)
        self.frame_VEDT_buttom.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(240, 240, 240);\n"
"}")
        self.frame_VEDT_buttom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_VEDT_buttom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_VEDT_buttom.setObjectName("frame_VEDT_buttom")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_VEDT_buttom)
        self.horizontalLayout_4.setContentsMargins(0, 0, 2, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_proyectos_EDT = QtWidgets.QFrame(self.frame_VEDT_buttom)
        self.frame_proyectos_EDT.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(240, 240, 240);\n"
"}")
        self.frame_proyectos_EDT.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_proyectos_EDT.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_proyectos_EDT.setObjectName("frame_proyectos_EDT")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_proyectos_EDT)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_2.setContentsMargins(2, 2, 1, 2)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_buscar = QtWidgets.QFrame(self.frame_proyectos_EDT)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_buscar.sizePolicy().hasHeightForWidth())
        self.frame_buscar.setSizePolicy(sizePolicy)
        self.frame_buscar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_buscar.setStyleSheet("border-radius:5px;")
        self.frame_buscar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_buscar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_buscar.setObjectName("frame_buscar")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_buscar)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.le_buscar = QtWidgets.QLineEdit(self.frame_buscar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_buscar.sizePolicy().hasHeightForWidth())
        self.le_buscar.setSizePolicy(sizePolicy)
        self.le_buscar.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.le_buscar.setFont(font)
        self.le_buscar.setToolTipDuration(-1)
        self.le_buscar.setAutoFillBackground(False)
        self.le_buscar.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"background-color: rgb(253, 253, 253);")
        self.le_buscar.setInputMethodHints(QtCore.Qt.ImhNone)
        self.le_buscar.setInputMask("")
        self.le_buscar.setText("")
        self.le_buscar.setMaxLength(35)
        self.le_buscar.setFrame(True)
        self.le_buscar.setClearButtonEnabled(True)
        self.le_buscar.setObjectName("texto_buscar")
        self.horizontalLayout_5.addWidget(self.le_buscar)
        self.pb_buscar = QtWidgets.QPushButton(self.frame_buscar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_buscar.sizePolicy().hasHeightForWidth())
        self.pb_buscar.setSizePolicy(sizePolicy)
        self.pb_buscar.setMinimumSize(QtCore.QSize(16, 16))
        self.pb_buscar.setMaximumSize(QtCore.QSize(30, 25))
        self.pb_buscar.setStyleSheet("""QPushButton:pressed{
	background-color:  rgb(220, 220, 220);
	border-radius:2px;
	border-style: outset;
	border: 0.5px solid;
	border-top-color : black; 
    border-left-color :black;
    border-right-color :black;
    border-bottom-color : black;
}

QPushButton:hover:!pressed{
	background-color: white;
}""")
        self.pb_buscar.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("images/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_buscar.setIcon(icon6)
        self.pb_buscar.setIconSize(QtCore.QSize(16, 16))
        self.pb_buscar.setObjectName("pb_buscar")
        self.horizontalLayout_5.addWidget(self.pb_buscar)
        self.verticalLayout_2.addWidget(self.frame_buscar)
        self.frame_arbol_proyectos = QtWidgets.QFrame(self.frame_proyectos_EDT)
        self.frame_arbol_proyectos.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_arbol_proyectos.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_arbol_proyectos.setObjectName("frame_arbol_proyectos")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_arbol_proyectos)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.vista_arbol_proyectos = QtWidgets.QTreeView(self.frame_arbol_proyectos)
        self.vista_arbol_proyectos.setAutoFillBackground(True)
        self.vista_arbol_proyectos.setStyleSheet("background-color: rgb(253, 253, 253);\n"
"border-radius:40px;")
        self.vista_arbol_proyectos.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.vista_arbol_proyectos.setFrameShadow(QtWidgets.QFrame.Plain)
        self.vista_arbol_proyectos.setLineWidth(1)
        self.vista_arbol_proyectos.setMidLineWidth(0)
        self.vista_arbol_proyectos.setObjectName("vista_arbol_proyectos")
        # do not show the modify the header columns
        self.vista_arbol_proyectos.header().setSectionResizeMode(QtWidgets.QHeaderView.ResizeToContents)

        self.verticalLayout_3.addWidget(self.vista_arbol_proyectos)
        self.verticalLayout_2.addWidget(self.frame_arbol_proyectos)
        self.horizontalLayout_4.addWidget(self.frame_proyectos_EDT)
        self.frame_EDT = QtWidgets.QFrame(self.frame_VEDT_buttom)
        self.frame_EDT.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(253, 253, 253);\n"
"}")
        self.frame_EDT.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_EDT.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_EDT.setObjectName("frame_EDT")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_EDT)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tab_EDT = QtWidgets.QTabWidget(self.frame_EDT)
        self.tab_EDT.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tab_EDT.setFont(font)
        self.tab_EDT.setStyleSheet("QTabWidget{\n"
"    \n"
"    font: 10pt \"Arial Rounded MT Bold\";\n"
"}")
        self.tab_EDT.setTabPosition(QtWidgets.QTabWidget.North)
        self.tab_EDT.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tab_EDT.setElideMode(QtCore.Qt.ElideNone)
        self.tab_EDT.setDocumentMode(False)
        self.tab_EDT.setTabsClosable(True)
        self.tab_EDT.setTabBarAutoHide(True)
        self.tab_EDT.setObjectName("tab_EDT")
        self.inicio = QtWidgets.QWidget()
        self.inicio.setObjectName("inicio")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.inicio)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lbl_inicio = QtWidgets.QLabel(self.inicio)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(36)
        self.lbl_inicio.setFont(font)
        self.lbl_inicio.setScaledContents(False)
        self.lbl_inicio.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_inicio.setWordWrap(True)
        self.lbl_inicio.setObjectName("lbl_inicio")
        self.verticalLayout_5.addWidget(self.lbl_inicio)
        self.tab_EDT.addTab(self.inicio, "")
        self.resultados = QtWidgets.QWidget()
        self.resultados.setObjectName("resultados")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.resultados)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_resultados = QtWidgets.QFrame(self.resultados)
        self.frame_resultados.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_resultados.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_resultados.setObjectName("frame_resultados")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_resultados)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(6)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.scrollArea = QtWidgets.QScrollArea(self.frame_resultados)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1049, 733))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_17 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_17.setStyleSheet("font: 14pt \"Arial Rounded MT Bold\";")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_17)
        self.gridLayout.setContentsMargins(5, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(5)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.cantidad_paneles = QtWidgets.QLabel(self.frame_17)
        self.cantidad_paneles.setEnabled(False)
        self.cantidad_paneles.setFrameShape(QtWidgets.QFrame.Box)
        self.cantidad_paneles.setText("")
        self.cantidad_paneles.setAlignment(QtCore.Qt.AlignCenter)
        self.cantidad_paneles.setObjectName("cantidad_paneles")
        self.gridLayout.addWidget(self.cantidad_paneles, 6, 1, 1, 1)
        self.fecha_vuelo = QtWidgets.QLabel(self.frame_17)
        self.fecha_vuelo.setEnabled(False)
        self.fecha_vuelo.setFrameShape(QtWidgets.QFrame.Box)
        self.fecha_vuelo.setFrameShadow(QtWidgets.QFrame.Plain)
        self.fecha_vuelo.setText("")
        self.fecha_vuelo.setAlignment(QtCore.Qt.AlignCenter)
        self.fecha_vuelo.setObjectName("fecha_vuelo")
        self.gridLayout.addWidget(self.fecha_vuelo, 1, 1, 1, 1)
        self.ancho_cubierto = QtWidgets.QLabel(self.frame_17)
        self.ancho_cubierto.setEnabled(False)
        self.ancho_cubierto.setFrameShape(QtWidgets.QFrame.Box)
        self.ancho_cubierto.setText("")
        self.ancho_cubierto.setAlignment(QtCore.Qt.AlignCenter)
        self.ancho_cubierto.setObjectName("ancho_cubierto")
        self.gridLayout.addWidget(self.ancho_cubierto, 2, 1, 1, 1)
        self.lbl_cantidad_paneles = QtWidgets.QLabel(self.frame_17)
        self.lbl_cantidad_paneles.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_cantidad_paneles.setObjectName("lbl_cantidad_paneles")
        self.gridLayout.addWidget(self.lbl_cantidad_paneles, 6, 0, 1, 1)
        self.lbl_overlap_vertical = QtWidgets.QLabel(self.frame_17)
        self.lbl_overlap_vertical.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_overlap_vertical.setObjectName("lbl_overlap_vertical")
        self.gridLayout.addWidget(self.lbl_overlap_vertical, 5, 0, 1, 1)
        self.alto_cubierto = QtWidgets.QLabel(self.frame_17)
        self.alto_cubierto.setEnabled(False)
        self.alto_cubierto.setFrameShape(QtWidgets.QFrame.Box)
        self.alto_cubierto.setText("")
        self.alto_cubierto.setAlignment(QtCore.Qt.AlignCenter)
        self.alto_cubierto.setObjectName("alto_cubierto")
        self.gridLayout.addWidget(self.alto_cubierto, 3, 1, 1, 1)
        self.paneles_defectuosos = QtWidgets.QLabel(self.frame_17)
        self.paneles_defectuosos.setEnabled(False)
        self.paneles_defectuosos.setFrameShape(QtWidgets.QFrame.Box)
        self.paneles_defectuosos.setText("")
        self.paneles_defectuosos.setAlignment(QtCore.Qt.AlignCenter)
        self.paneles_defectuosos.setObjectName("paneles_defectuosos")
        self.gridLayout.addWidget(self.paneles_defectuosos, 7, 1, 1, 1)
        self.lbl_fecha_vuelo = QtWidgets.QLabel(self.frame_17)
        self.lbl_fecha_vuelo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_fecha_vuelo.setObjectName("lbl_fecha_vuelo")
        self.gridLayout.addWidget(self.lbl_fecha_vuelo, 1, 0, 1, 1)
        self.lbl_paneles_defectuosos = QtWidgets.QLabel(self.frame_17)
        self.lbl_paneles_defectuosos.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_paneles_defectuosos.setObjectName("lbl_paneles_defectuosos")
        self.gridLayout.addWidget(self.lbl_paneles_defectuosos, 7, 0, 1, 1)
        self.lbl_ancho_cubierto = QtWidgets.QLabel(self.frame_17)
        self.lbl_ancho_cubierto.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_ancho_cubierto.setObjectName("lbl_ancho_cubierto")
        self.gridLayout.addWidget(self.lbl_ancho_cubierto, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 8, 0, 1, 1)
        self.overlap_vertical = QtWidgets.QLabel(self.frame_17)
        self.overlap_vertical.setEnabled(False)
        self.overlap_vertical.setFrameShape(QtWidgets.QFrame.Box)
        self.overlap_vertical.setText("")
        self.overlap_vertical.setAlignment(QtCore.Qt.AlignCenter)
        self.overlap_vertical.setObjectName("overlap_vertical")
        self.gridLayout.addWidget(self.overlap_vertical, 5, 1, 1, 1)
        self.lbl_overlap_horizontal = QtWidgets.QLabel(self.frame_17)
        self.lbl_overlap_horizontal.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_overlap_horizontal.setObjectName("lbl_overlap_horizontal")
        self.gridLayout.addWidget(self.lbl_overlap_horizontal, 4, 0, 1, 1)
        self.overlap_horizontal = QtWidgets.QLabel(self.frame_17)
        self.overlap_horizontal.setEnabled(False)
        self.overlap_horizontal.setFrameShape(QtWidgets.QFrame.Box)
        self.overlap_horizontal.setText("")
        self.overlap_horizontal.setAlignment(QtCore.Qt.AlignCenter)
        self.overlap_horizontal.setObjectName("overlap_horizontal")
        self.gridLayout.addWidget(self.overlap_horizontal, 4, 1, 1, 1)
        self.lbl_alto_cubierto = QtWidgets.QLabel(self.frame_17)
        self.lbl_alto_cubierto.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_alto_cubierto.setObjectName("lbl_alto_cubierto")
        self.gridLayout.addWidget(self.lbl_alto_cubierto, 3, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 7, 2, 1, 1)
        self.lbl_nombre_proyecto = QtWidgets.QLabel(self.frame_17)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_nombre_proyecto.setFont(font)
        self.lbl_nombre_proyecto.setStyleSheet("font: 20pt \"Arial Rounded MT Bold\";")
        self.lbl_nombre_proyecto.setObjectName("lbl_nombre_proyecto")
        self.gridLayout.addWidget(self.lbl_nombre_proyecto, 0, 0, 1, 1)
        self.nombe_proyecto = QtWidgets.QLabel(self.frame_17)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.nombe_proyecto.setFont(font)
        self.nombe_proyecto.setStyleSheet("font: 20pt \"Arial Rounded MT Bold\";")
        self.nombe_proyecto.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.nombe_proyecto.setFrameShadow(QtWidgets.QFrame.Plain)
        self.nombe_proyecto.setText("")
        self.nombe_proyecto.setAlignment(QtCore.Qt.AlignCenter)
        self.nombe_proyecto.setObjectName("nombe_proyecto")
        self.gridLayout.addWidget(self.nombe_proyecto, 0, 1, 1, 2)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 3)
        self.gridLayout.setColumnStretch(2, 5)
        self.verticalLayout_14.addWidget(self.frame_17)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_12.addWidget(self.scrollArea)
        self.verticalLayout_10.addWidget(self.frame_resultados)
        self.tab_EDT.addTab(self.resultados, "")
        self.ortofotoRGB = QtWidgets.QWidget()
        self.ortofotoRGB.setObjectName("ortofotoRGB")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.ortofotoRGB)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_orto_rgb = QtWidgets.QFrame(self.ortofotoRGB)
        self.frame_orto_rgb.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_orto_rgb.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_orto_rgb.setObjectName("frame_orto_rgb")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_orto_rgb)
        self.verticalLayout_7.setContentsMargins(0, 2, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_rgb_top = QtWidgets.QFrame(self.frame_orto_rgb)
        self.frame_rgb_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_rgb_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_rgb_top.setObjectName("frame_rgb_top")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_rgb_top)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.checkBox = QtWidgets.QCheckBox(self.frame_rgb_top)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        self.checkBox.setFont(font)
        self.checkBox.setIconSize(QtCore.QSize(30, 30))
        self.checkBox.setChecked(True)
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_6.addWidget(self.checkBox)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.verticalLayout_7.addWidget(self.frame_rgb_top)
        self.frame_rgb_buttom = QtWidgets.QFrame(self.frame_orto_rgb)
        self.frame_rgb_buttom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_rgb_buttom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_rgb_buttom.setObjectName("frame_rgb_buttom")
        self.verticalLayout_7.addWidget(self.frame_rgb_buttom)
        self.verticalLayout_7.setStretch(0, 1)
        self.verticalLayout_7.setStretch(1, 100)
        self.verticalLayout_6.addWidget(self.frame_orto_rgb)
        self.tab_EDT.addTab(self.ortofotoRGB, "")
        self.ortofotoTermica = QtWidgets.QWidget()
        self.ortofotoTermica.setObjectName("ortofotoTermica")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.ortofotoTermica)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_orto_termica = QtWidgets.QFrame(self.ortofotoTermica)
        self.frame_orto_termica.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_orto_termica.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_orto_termica.setObjectName("frame_orto_termica")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_orto_termica)
        self.verticalLayout_9.setContentsMargins(0, 2, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_termica_top = QtWidgets.QFrame(self.frame_orto_termica)
        self.frame_termica_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_termica_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_termica_top.setObjectName("frame_termica_top")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_termica_top)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame_termica_top)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_2.sizePolicy().hasHeightForWidth())
        self.checkBox_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setIconSize(QtCore.QSize(30, 30))
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setTristate(False)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_7.addWidget(self.checkBox_2)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.verticalLayout_9.addWidget(self.frame_termica_top)
        self.frame_termica_buttom = QtWidgets.QFrame(self.frame_orto_termica)
        self.frame_termica_buttom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_termica_buttom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_termica_buttom.setObjectName("frame_termica_buttom")
        self.verticalLayout_9.addWidget(self.frame_termica_buttom)
        self.verticalLayout_9.setStretch(0, 1)
        self.verticalLayout_9.setStretch(1, 100)
        self.verticalLayout_8.addWidget(self.frame_orto_termica)
        self.tab_EDT.addTab(self.ortofotoTermica, "")
        self.graficas = QtWidgets.QWidget()
        self.graficas.setObjectName("graficas")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.graficas)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_grafica = QtWidgets.QFrame(self.graficas)
        self.frame_grafica.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_grafica.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_grafica.setObjectName("frame_grafica")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_grafica)
        self.verticalLayout_15.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_15.setSpacing(1)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.lbl_titul_tab_grafica = QtWidgets.QLabel(self.frame_grafica)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_titul_tab_grafica.sizePolicy().hasHeightForWidth())
        self.lbl_titul_tab_grafica.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(20)
        self.lbl_titul_tab_grafica.setFont(font)
        self.lbl_titul_tab_grafica.setScaledContents(False)
        self.lbl_titul_tab_grafica.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_titul_tab_grafica.setWordWrap(False)
        self.lbl_titul_tab_grafica.setObjectName("lbl_titul_tab_grafica")
        self.verticalLayout_15.addWidget(self.lbl_titul_tab_grafica)
        self.frame_grafica_buttom = QtWidgets.QFrame(self.frame_grafica)
        self.frame_grafica_buttom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_grafica_buttom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_grafica_buttom.setObjectName("frame_grafica_buttom")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_grafica_buttom)
        self.verticalLayout_16.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_16.setSpacing(2)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.frame_datos = QtWidgets.QFrame(self.frame_grafica_buttom)
        self.frame_datos.setStyleSheet("font: 14pt \"Arial Rounded MT Bold\";")
        self.frame_datos.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_datos.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_datos.setObjectName("frame_datos")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_datos)
        self.horizontalLayout.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_datos_x_grafica = QtWidgets.QLabel(self.frame_datos)
        self.lbl_datos_x_grafica.setObjectName("lbl_datos_x_grafica")
        self.horizontalLayout.addWidget(self.lbl_datos_x_grafica)
        self.cb_datos_x = QtWidgets.QComboBox(self.frame_datos)
        self.cb_datos_x.setObjectName("cb_datos_x")
        self.horizontalLayout.addWidget(self.cb_datos_x)
        self.lbl_datos_y_grafica = QtWidgets.QLabel(self.frame_datos)
        self.lbl_datos_y_grafica.setObjectName("lbl_datos_y_grafica")
        self.horizontalLayout.addWidget(self.lbl_datos_y_grafica)
        self.cb_datos_y = QtWidgets.QComboBox(self.frame_datos)
        self.cb_datos_y.setObjectName("cb_datos_y")
        self.horizontalLayout.addWidget(self.cb_datos_y)
        self.pb_actualizar = QtWidgets.QPushButton(self.frame_datos)
        self.pb_actualizar.setObjectName("pb_actualizar")
        self.horizontalLayout.addWidget(self.pb_actualizar)
        self.pb_guardar = QtWidgets.QPushButton(self.frame_datos)
        self.pb_guardar.setObjectName("pb_guardar")
        self.horizontalLayout.addWidget(self.pb_guardar)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 6)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(3, 6)
        self.horizontalLayout.setStretch(4, 3)
        self.horizontalLayout.setStretch(5, 2)
        self.verticalLayout_16.addWidget(self.frame_datos)
        self.frame_grafica_imagen = QtWidgets.QFrame(self.frame_grafica_buttom)
        self.frame_grafica_imagen.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_grafica_imagen.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_grafica_imagen.setObjectName("frame_grafica_imagen")
        self.verticalLayout_16.addWidget(self.frame_grafica_imagen)
        self.verticalLayout_16.setStretch(0, 1)
        self.verticalLayout_16.setStretch(1, 14)
        self.verticalLayout_15.addWidget(self.frame_grafica_buttom)
        self.verticalLayout_15.setStretch(0, 1)
        self.verticalLayout_15.setStretch(1, 20)
        self.verticalLayout_11.addWidget(self.frame_grafica)
        self.tab_EDT.addTab(self.graficas, "")
        self.verticalLayout_4.addWidget(self.tab_EDT)
        self.horizontalLayout_4.addWidget(self.frame_EDT)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 6)
        self.horizontalLayout_3.addWidget(self.frame_VEDT_buttom)
        self.verticalLayout.addWidget(self.frame_2)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 25)
        self.verticalLayout_13.addWidget(self.frame_VEDT)
        VEDT.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(VEDT)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1244, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        self.menubar.setPalette(palette)
        self.menubar.setStyleSheet("background-color: rgb(245, 245, 245);")
        self.menubar.setObjectName("menubar")
        self.menuEDT = QtWidgets.QMenu(self.menubar)
        self.menuEDT.setObjectName("menuEDT")
        self.menuProyecto = QtWidgets.QMenu(self.menubar)
        self.menuProyecto.setObjectName("menuProyecto")
        self.menuReporte = QtWidgets.QMenu(self.menubar)
        self.menuReporte.setObjectName("menuReporte")
        self.menuAyuda = QtWidgets.QMenu(self.menubar)
        self.menuAyuda.setObjectName("menuAyuda")
        VEDT.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(VEDT)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusbar.sizePolicy().hasHeightForWidth())
        self.statusbar.setSizePolicy(sizePolicy)
        self.statusbar.setObjectName("statusbar")
        VEDT.setStatusBar(self.statusbar)
        self.EDT_cambiar = QtWidgets.QAction(VEDT)
        self.EDT_cambiar.setObjectName("EDT_cambiar")
        self.actionGuardar = QtWidgets.QAction(VEDT)
        self.actionGuardar.setObjectName("actionGuardar")
        self.actionGuardar_como = QtWidgets.QAction(VEDT)
        self.actionGuardar_como.setObjectName("actionGuardar_como")
        self.actionEliminar = QtWidgets.QAction(VEDT)
        self.proyecto_eliminar = QtWidgets.QAction(VEDT)
        self.proyecto_eliminar.setObjectName("proyecto_eliminar")
        self.actionSalir = QtWidgets.QAction(VEDT)
        self.actionSalir.setObjectName("actionSalir")
        self.actionEstablecer_correo = QtWidgets.QAction(VEDT)
        self.actionEstablecer_correo.setObjectName("actionEstablecer_correo")
        self.reporte_imprimir = QtWidgets.QAction(VEDT)
        self.reporte_imprimir.setObjectName("reporte_imprimir")
        self.reporte_compartir = QtWidgets.QAction(VEDT)
        self.reporte_compartir.setObjectName("reporte_compartir")
        self.proyecto_nuevo = QtWidgets.QAction(VEDT)
        self.proyecto_nuevo.setObjectName("proyecto_nuevo")
        self.proyecto_iniciar = QtWidgets.QAction(VEDT)
        self.proyecto_iniciar.setObjectName("proyecto_iniciar")
        self.proyecto_propiedades = QtWidgets.QAction(VEDT)
        self.proyecto_propiedades.setObjectName("proyecto_propiedades")
        self.EDT_establecer_correo = QtWidgets.QAction(VEDT)
        self.EDT_establecer_correo.setObjectName("EDT_establecer_correo")
        self.EDT_nuevo = QtWidgets.QAction(VEDT)
        self.EDT_nuevo.setObjectName("EDT_nuevo")
        self.proyecto_guardar = QtWidgets.QAction(VEDT)
        self.proyecto_guardar.setObjectName("proyecto_guardar")
        self.proyecto_guardar_como = QtWidgets.QAction(VEDT)
        self.proyecto_guardar_como.setObjectName("proyecto_guardar_como")
        self.proyecto_abrir = QtWidgets.QAction(VEDT)
        self.proyecto_abrir.setObjectName("proyecto_abrir")
        self.reporte_abrir = QtWidgets.QAction(VEDT)
        self.reporte_abrir.setObjectName("reporte_abrir")
        self.reporte_ver_grafica = QtWidgets.QAction(VEDT)
        self.reporte_ver_grafica.setObjectName("reporte_ver_grafica")
        self.reporte_guardar_grafica = QtWidgets.QAction(VEDT)
        self.reporte_guardar_grafica.setObjectName("reporte_guardar_grafica")
        self.reporte_eliminar = QtWidgets.QAction(VEDT)
        self.reporte_eliminar.setObjectName("reporte_eliminar")
        self.EDT_eliminar = QtWidgets.QAction(VEDT)
        self.EDT_eliminar.setObjectName("EDT_eliminar")
        self.ayuda_ayuda = QtWidgets.QAction(VEDT)
        self.ayuda_ayuda.setObjectName("ayuda_ayuda")
        self.menuEDT.addAction(self.EDT_nuevo)
        self.menuEDT.addAction(self.EDT_cambiar)
        self.menuEDT.addAction(self.EDT_eliminar)
        self.menuEDT.addSeparator()
        self.menuEDT.addAction(self.EDT_establecer_correo)
        self.menuProyecto.addAction(self.proyecto_nuevo)
        self.menuProyecto.addAction(self.proyecto_abrir)
        self.menuProyecto.addAction(self.proyecto_guardar)
        self.menuProyecto.addAction(self.proyecto_guardar_como)
        self.menuProyecto.addAction(self.proyecto_eliminar)
        self.menuProyecto.addSeparator()
        self.menuProyecto.addAction(self.proyecto_iniciar)
        self.menuProyecto.addAction(self.proyecto_propiedades)
        self.menuReporte.addAction(self.reporte_abrir)
        self.menuReporte.addAction(self.reporte_imprimir)
        self.menuReporte.addAction(self.reporte_compartir)
        self.menuReporte.addAction(self.reporte_eliminar)
        self.menuReporte.addSeparator()
        self.menuReporte.addAction(self.reporte_ver_grafica)
        self.menuReporte.addAction(self.reporte_guardar_grafica)
        self.menuAyuda.addAction(self.ayuda_ayuda)
        self.menubar.addAction(self.menuProyecto.menuAction())
        self.menubar.addAction(self.menuEDT.menuAction())
        self.menubar.addAction(self.menuReporte.menuAction())
        self.menubar.addAction(self.menuAyuda.menuAction())
        # change color of the menu bar only when the mouse is over it
        self.menubar.setStyleSheet("QMenuBar::item {background-color: transparent;}")
        self.menubar.setStyleSheet("QMenuBar::item:selected {background-color: transparent;}")
        self.menubar.setStyleSheet("QMenuBar::item:pressed {background-color: transparent;}")

        self.retranslateUi(VEDT)
        self.tab_EDT.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(VEDT)

        # hide tab resultados
        self.tab_EDT.setTabEnabled(1, False)
        # hide tab ortofoto rgb and termica
        self.tab_EDT.setTabEnabled(2, False)
        self.tab_EDT.setTabEnabled(3, False)
        # hide tab grafica
        self.tab_EDT.setTabEnabled(4, False)

    def retranslateUi(self, VEDT):
        _translate = QtCore.QCoreApplication.translate
        VEDT.setWindowTitle(_translate("VEDT", "SIPaF"))
        self.pb_crear_proyecto.setToolTip(_translate("VEDT", "Crear nuevo proyecto"))
        self.pb_editar_propiedades.setToolTip(_translate("VEDT", "Propiedades del proyecto"))
        self.pb_iniciar_proceso.setToolTip(_translate("VEDT", "Iniciar el proyecto"))
        self.pb_imprimir.setToolTip(_translate("VEDT", "Imprimir reporte"))
        self.pb_comparar.setToolTip(_translate("VEDT", "Comparar reportes"))
        self.le_buscar.setToolTip(_translate("VEDT", "Ingresar nombre de archivo"))
        self.le_buscar.setPlaceholderText(_translate("VEDT", " Buscar...."))
        self.pb_buscar.setToolTip(_translate("VEDT", "Buscar en EDT"))
        self.lbl_inicio.setText(_translate("VEDT", "Bienvenido, inicie o abra un proyecto."))
        self.tab_EDT.setTabText(self.tab_EDT.indexOf(self.inicio), _translate("VEDT", "Inicio"))
        self.lbl_cantidad_paneles.setText(_translate("VEDT", "Cantidad de paneles:"))
        self.lbl_overlap_vertical.setText(_translate("VEDT", "Overlap vertical:"))
        self.lbl_fecha_vuelo.setText(_translate("VEDT", "Fecha del vuelo:"))
        self.lbl_paneles_defectuosos.setText(_translate("VEDT", "Paneles defectuosos:"))
        self.lbl_ancho_cubierto.setText(_translate("VEDT", "Ancho cubierto:"))
        self.lbl_overlap_horizontal.setText(_translate("VEDT", "Overlap horizontal:"))
        self.lbl_alto_cubierto.setText(_translate("VEDT", "Alto cubierto:"))
        self.lbl_nombre_proyecto.setText(_translate("VEDT", "Nombre del proyecto:"))
        self.tab_EDT.setTabText(self.tab_EDT.indexOf(self.resultados), _translate("VEDT", "Resultados"))
        self.checkBox.setText(_translate("VEDT", "Mostrar ortofoto RGB con paneles solares dañados identificados"))
        self.tab_EDT.setTabText(self.tab_EDT.indexOf(self.ortofotoRGB), _translate("VEDT", "Ortofoto RGB"))
        self.checkBox_2.setText(_translate("VEDT", "Mostrar ortofoto térmica con paneles solares dañados identificados"))
        self.tab_EDT.setTabText(self.tab_EDT.indexOf(self.ortofotoTermica), _translate("VEDT", "Ortofoto Térmica"))
        self.lbl_titul_tab_grafica.setText(_translate("VEDT", "Gráfica entre proyectos sleccionados"))
        self.lbl_datos_x_grafica.setText(_translate("VEDT", "Datos en X:"))
        self.lbl_datos_y_grafica.setText(_translate("VEDT", "Datos en Y:"))
        self.pb_actualizar.setText(_translate("VEDT", "Acutalizar"))
        self.pb_guardar.setText(_translate("VEDT", "Guardar"))
        self.tab_EDT.setTabText(self.tab_EDT.indexOf(self.graficas), _translate("VEDT", "Gráficas"))
        self.menuEDT.setTitle(_translate("VEDT", "EDT"))
        self.menuProyecto.setTitle(_translate("VEDT", "Proyecto"))
        self.menuReporte.setTitle(_translate("VEDT", "Reporte"))
        self.menuAyuda.setTitle(_translate("VEDT", "Ayuda"))
        self.EDT_cambiar.setText(_translate("VEDT", "Cambiar"))
        self.actionGuardar.setText(_translate("VEDT", "Guardar"))
        self.actionGuardar_como.setText(_translate("VEDT", "Guardar como..."))
        self.actionSalir.setText(_translate("VEDT", "Salir"))
        self.actionEstablecer_correo.setText(_translate("VEDT", "Cambiar"))
        self.reporte_imprimir.setText(_translate("VEDT", "Imprimir"))
        self.reporte_compartir.setText(_translate("VEDT", "Compartir"))
        self.proyecto_nuevo.setText(_translate("VEDT", "Nuevo"))
        self.proyecto_eliminar.setText(_translate("VEDT", "Eliminar"))
        self.proyecto_iniciar.setText(_translate("VEDT", "Iniciar"))
        self.proyecto_propiedades.setText(_translate("VEDT", "Propiedades"))
        self.EDT_establecer_correo.setText(_translate("VEDT", "Establecer correo"))
        self.EDT_nuevo.setText(_translate("VEDT", "Nuevo"))
        self.proyecto_guardar.setText(_translate("VEDT", "Guardar"))
        self.proyecto_guardar_como.setText(_translate("VEDT", "Guardar como..."))
        self.proyecto_abrir.setText(_translate("VEDT", "Abrir"))
        self.reporte_abrir.setText(_translate("VEDT", "Abrir"))
        self.reporte_eliminar.setText(_translate("VEDT", "Eliminar"))
        self.reporte_ver_grafica.setText(_translate("VEDT", "Ver gráfica"))
        self.reporte_guardar_grafica.setText(_translate("VEDT", "Guardar gráfica"))
        self.EDT_eliminar.setText(_translate("VEDT", "Eliminar"))
        self.ayuda_ayuda.setText(_translate("VEDT", "Ayuda"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     VEDT = QtWidgets.QMainWindow()
#     ui = Ui_VEDT()
#     ui.setupUi(VEDT)
#     VEDT.show()
#     sys.exit(app.exec_())

