# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VistaGestionarEDT.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_VGestionarEDT(object):
    def setupUi(self, VGestionarEDT):
        VGestionarEDT.setObjectName("VGestionarEDT")
        # open as modal window
        VGestionarEDT.setWindowModality(QtCore.Qt.ApplicationModal)
        VGestionarEDT.setEnabled(True)
        VGestionarEDT.resize(735, 135)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(VGestionarEDT.sizePolicy().hasHeightForWidth())
        VGestionarEDT.setSizePolicy(sizePolicy)
        VGestionarEDT.setMinimumSize(QtCore.QSize(735, 135))
        VGestionarEDT.setMaximumSize(QtCore.QSize(735, 135))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        VGestionarEDT.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/SiPaF.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        VGestionarEDT.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(VGestionarEDT)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_principal = QtWidgets.QFrame(VGestionarEDT)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_principal.sizePolicy().hasHeightForWidth())
        self.frame_principal.setSizePolicy(sizePolicy)
        self.frame_principal.setMinimumSize(QtCore.QSize(750, 135))
        self.frame_principal.setMaximumSize(QtCore.QSize(16777215, 135))
        self.frame_principal.setStyleSheet("background-color: rgb(240, 240, 240);")#	background-color: rgb(240, 240, 240);
        self.frame_principal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_principal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_principal.setObjectName("frame_principal")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_principal)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.frame_principal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.frame.setFont(font)
        self.frame.setStyleSheet("font: 16pt \"Arial Rounded MT Bold\";")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 15, 0)
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_guardarEn = QtWidgets.QLabel(self.frame)
        self.label_guardarEn.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label_guardarEn)
        self.label_carpeta = QtWidgets.QLabel(self.frame)
        self.label_carpeta.setAlignment(QtCore.Qt.AlignCenter)
        self.label_carpeta.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_carpeta)
        self.pb_folder = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_folder.sizePolicy().hasHeightForWidth())
        self.pb_folder.setSizePolicy(sizePolicy)
        self.pb_folder.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_folder.setIcon(icon1)
        self.pb_folder.setObjectName("pb_folder")
        self.horizontalLayout_3.addWidget(self.pb_folder)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 5)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_seleccionarEDT = QtWidgets.QFrame(self.frame_principal)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.frame_seleccionarEDT.setFont(font)
        self.frame_seleccionarEDT.setStyleSheet("font: 16pt \"Arial Rounded MT Bold\";")
        self.frame_seleccionarEDT.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_seleccionarEDT.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_seleccionarEDT.setObjectName("frame_seleccionarEDT")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_seleccionarEDT)
        self.horizontalLayout_2.setContentsMargins(0, 0, 12, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_nombreEDT = QtWidgets.QLabel(self.frame_seleccionarEDT)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_nombreEDT.sizePolicy().hasHeightForWidth())
        self.label_nombreEDT.setSizePolicy(sizePolicy)
        self.label_nombreEDT.setMinimumSize(QtCore.QSize(0, 30))
        self.label_nombreEDT.setMaximumSize(QtCore.QSize(325, 30))
        self.label_nombreEDT.setObjectName("label_nombreEDT")
        self.horizontalLayout_2.addWidget(self.label_nombreEDT)
        self.comboBox_EDT = QtWidgets.QComboBox(self.frame_seleccionarEDT)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_EDT.sizePolicy().hasHeightForWidth())
        self.comboBox_EDT.setSizePolicy(sizePolicy)
        self.comboBox_EDT.setMinimumSize(QtCore.QSize(410, 30))
        self.comboBox_EDT.setMaximumSize(QtCore.QSize(400, 30))
        self.comboBox_EDT.setStatusTip("")
        self.comboBox_EDT.setEditable(True)
        self.comboBox_EDT.setObjectName("comboBox_EDT")
        self.horizontalLayout_2.addWidget(self.comboBox_EDT)
        self.verticalLayout_2.addWidget(self.frame_seleccionarEDT)
        self.frame_botones = QtWidgets.QFrame(self.frame_principal)
        self.frame_botones.setStyleSheet("QPushButton{\n"
"    font: 16pt \"Arial Rounded MT Bold\";\n"
"    border-radius:10px;\n"
"    background-color:rgb(0, 80, 171);\n"
"color: rgb(255, 255, 255)\n"
"}\n"
"rgb(0, 80, 171)")
        self.frame_botones.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_botones.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_botones.setObjectName("frame_botones")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_botones)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(10, 0, 0, 0)
        self.horizontalLayout.setSpacing(30)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pb_crear = QtWidgets.QPushButton(self.frame_botones)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_crear.sizePolicy().hasHeightForWidth())
        self.pb_crear.setSizePolicy(sizePolicy)
        self.pb_crear.setMinimumSize(QtCore.QSize(140, 40))
        self.pb_crear.setMaximumSize(QtCore.QSize(60, 35))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pb_crear.setFont(font)
        self.pb_crear.setStyleSheet("")
        self.pb_crear.setObjectName("pb_crear")
        self.horizontalLayout.addWidget(self.pb_crear)
        self.pb_eliminar = QtWidgets.QPushButton(self.frame_botones)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_eliminar.sizePolicy().hasHeightForWidth())
        self.pb_eliminar.setSizePolicy(sizePolicy)
        self.pb_eliminar.setMinimumSize(QtCore.QSize(105, 40))
        self.pb_eliminar.setMaximumSize(QtCore.QSize(60, 35))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pb_eliminar.setFont(font)
        self.pb_eliminar.setStyleSheet("")
        self.pb_eliminar.setObjectName("pb_eliminar")
        self.horizontalLayout.addWidget(self.pb_eliminar)
        self.pb_cancelar = QtWidgets.QPushButton(self.frame_botones)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_cancelar.sizePolicy().hasHeightForWidth())
        self.pb_cancelar.setSizePolicy(sizePolicy)
        self.pb_cancelar.setMinimumSize(QtCore.QSize(105, 40))
        self.pb_cancelar.setMaximumSize(QtCore.QSize(60, 35))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pb_cancelar.setFont(font)
        self.pb_cancelar.setStyleSheet("")
        self.pb_cancelar.setObjectName("pb_cancelar")
        self.horizontalLayout.addWidget(self.pb_cancelar)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.frame_botones)
        self.verticalLayout.addWidget(self.frame_principal)

        self.retranslateUi(VGestionarEDT)
        QtCore.QMetaObject.connectSlotsByName(VGestionarEDT)

    def retranslateUi(self, VGestionarEDT):
        _translate = QtCore.QCoreApplication.translate
        VGestionarEDT.setWindowTitle(_translate("VGestionarEDT", "Gestionar EDT"))
        self.label_guardarEn.setText(_translate("VGestionarEDT", "Guardar en: "))
        self.label_carpeta.setText(_translate("VGestionarEDT", "Elegir carpeta"))
        self.label_nombreEDT.setText(_translate("VGestionarEDT", "Nombre del espacio de trabajo: "))
        self.comboBox_EDT.setCurrentText(_translate("VGestionarEDT", "Seleccione espacio o cree uno nuevo"))
        #self.comboBox_EDT.setPlaceholderText(_translate("VGestionarEDT", "Only alphanumeric characters and underscores."))
        self.pb_crear.setText(_translate("VGestionarEDT", "Crear"))
        self.pb_eliminar.setText(_translate("VGestionarEDT", "Eliminar"))
        self.pb_cancelar.setText(_translate("VGestionarEDT", "Cancelar"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     VGestionarEDT = QtWidgets.QWidget()
#     ui = Ui_VGestionarEDT()
#     ui.setupUi(VGestionarEDT)
#     VGestionarEDT.show()
#     sys.exit(app.exec_())

